### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [Unity-Bedrock/Pooler#1]
Git tag: 0.0.2
package.json version: 0.0.1 https://github.com/Unity-Bedrock/Pooler/blob/0.0.2/Assets/Pooler/package.json

To fix: bump version then re-tag 0.0.2

Issue detected by https://openupm.com/packages/com.unity-bedrock.pooler/?subPage=pipelines

**Comment by feko006** [comment]
Package version updated.
